# Generated by Django 3.0.9 on 2020-08-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='area_width',
            field=models.IntegerField(default=0),
        ),
    ]
