# Generated by Django 3.0.9 on 2020-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200807_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_slide',
            field=models.BooleanField(default=False),
        ),
    ]
