version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=supersecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - ACTIVE_SETTING=prod
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: grahadb
      POSTGRES_USER: yoongyeong
      POSTGRES_PASSWORD: postgres123

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:8080"
    depends_on:
      - app

volumes:
  static_data: